### ISSUE TITLE
LAMMPS Incompatabilty (MARCH 2023)

### ISSUE THREAD

**Issue by JasonGibsonUfl** [uf3/uf3#102] opened 2023-11-20 19:45 UTC
The most recent LAMMPS plug-in on the development branch was tested with the LAMMPS version published, March 24,  2022. The LAMMPS version that was published on March 28, 2023 has changed some of the core functions used by UF3-LAMMPS. Currently, the following input causes an error.

```
pair_style uf3 3 2

pair_coeff 1 1 N_N
pair_coeff 1 2 N_Si
pair_coeff 2 2 Si_Si

pair_coeff 1 1 1 N_N_N
pair_coeff 1 1 2 N_N_Si
pair_coeff 1 2 2 N_Si_Si
pair_coeff 2 1 1 Si_N_N
pair_coeff 2 1 2 Si_N_Si
pair_coeff 2 2 2 Si_Si_Si
```

This input produces the following error:

```
ERROR: UF3: Not all 3-body UF potentials are set, 
                    missing potential file for 2-1-1 interaction (src/ML-UF3/pair_uf3.cpp:920)
```
The log file suggests that the current implementation incorrectly sets the 2-1-1 interaction file to capture 1-2-1 interactions:

```
73 pair_coeff 2 1 1 /blue/hennig/jasongibson/IPAM_mlip_hackathon/uf3_mlip/uf3_lammps_pot_gaussian_comp_low_e_35_V2/Si_N_N
 74                                                                                 
 75 UF3: Opening /blue/hennig/jasongibson/IPAM_mlip_hackathon/uf3_mlip/uf3_lammps_pot_gaussian_comp_low_e_35_V2/Si_N_N file
 76 UF3: /blue/hennig/jasongibson/IPAM_mlip_hackathon/uf3_mlip/uf3_lammps_pot_gaussian_comp_low_e_35_V2/Si_N_N file should contain UF3 potenti    al for 1 2 1
```

**Comment by monk-04** [comment] 2023-11-20 20:21
Duplicate of #101

**Comment by monk-04** [comment] 2023-11-27 19:45
Closing this Issue, marking it resolved!

**Closed as completed by monk-04** 2023-11-27 19:45 UTC
Labels: bug
